### ISSUE TITLE
Add tracing to ANCM

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#108]
@davidfowl, @pan-wang and I met to discuss adding ETW tracing to ANCM.
Currently the lack of trace identifiers makes it difficult to correlate requests in the FREB log to requests in ASP.NET Core which makes investigating failures extremely difficult.

**Comment by pan-wang** [comment]
Had some prototype with ETW worked

**Comment by muratg** [comment]
@pan-wang Could you share the details of your initial prototype?

**Comment by pan-wang** [comment]
@muratg  After prototyping, I realized that ETW cannot be handled well for the scenario that both IIS and IIS Express have ANCM installed. This is because the ETW manifest file does not have a version control and will be singleton per machine. So we decide to switch back to the old window logging mechanism so that we can have different event provider name at runtime to distinguish the event sources.

**Comment by pan-wang** [comment]
for tracing, we will enable file logging for stderr be default (and delete the file later if no error was logged).
We will add more log entries for in-process and out-of-process. This logging work will be added soon as part of refactoring

**Comment by shirhatti** [comment]
We have a new uber issue tracking all diagnostics work
