### ISSUE TITLE
Serviceworker errors when browser launched from IDE

### ISSUE THREAD

**Issue by vivphillips** [aspnet/AspNetCoreModule#139]
Using VS2017 with Kestrel.  If I start debugging from VS2017 then the serviceworker does not create cacheStorage folders on disk and all calls to cache.put() and cache.addAll() fail. IndexedDB works though...

If I then open a new browser window and navigate to the localhost url then serviceworker performs as expected.

How can I avoid this problem?

**Comment by Tratcher** [comment]
serviceworker?

**Comment by Tratcher** [comment]
Try this:
https://www.johanbostrom.se/blog/how-to-disable-the-built-in-chrome-from-starting-when-debugging-in-visual-studio-2017/

**Comment by vivphillips** [comment]
I don't want to disable it (having no remote means no Ide debugging or code changes) - I just want it to work.  I think the problem is related to the fact the VS starts Chrome with a custom profile (apparently required).  I think I've found the file location used for the Chrome -user-data-directory at AppData/Local/Microsoft/VisualStudio/versionNo/WebTools/ChromeData+guid.  One of those folders is used and contains the Default/ServiceWorker/CacheStorage folder for the url.  Only problem seems to be that Chrome can't (or won't) write to it........

**Comment by Tratcher** [comment]
@BillHiebert

**Comment by digeff** [comment]
@vivphillips The way that Chrome works is:

1. You can only tell Chrome to enable the “Debugging Mode” (which we require to debug the webpage) when the chrome.exe process/instance it’s first launched. It cannot be changed afterwards.
2. If you try to open a new chrome.exe instance, and there is an already existing chrome.exe instance that uses the same user profile, it will instead of launching the new chrome.exe instance, reuse the existing one.

What you can do if you want to use a specific user-data-directory while debugging from Visual Studio 2017 with ASP.NET is you can go to IIS Express -> Browse With -> Add. Add an option to launch chrome.exe with the --user-data-dir argument you want to use.

For the reasons stated earlier, if you have a chrome.exe instance already running with that same --user-data-dir, then debugging won't work, so you'll need to close each of those chrome.exe instances before starting to debug, and close it, or kill it. In particular, if you want to use your "default" --user-data-dir for debugging, that will probably mean that you need to close all your chrome.exe instances before you start debugging each time.

**Comment by vivphillips** [comment]
I understand your points but:

Scenario A:
No instance of Chrome open.
Run VS debug wth Chrome as the default browser
Cache.open() succeeds but Cache.put() fails.

Scenario B:
No instance of Chrome open.
Run VS debug with a different default browser (e.g. Edge)
Open an instance of Chrome from the desktop and navigate to the localhost url.
Cache.put() succeeds.

BTW: Do you know where the configuration settings  for launching chrome are in VS ?

**Comment by digeff** [comment]
Do you mean: "IIS Express -> Browse With -> Add"?

**Comment by vivphillips** [comment]
I'm using the default Chrome launch configuration (i.e. not adding one with my own command line parameters). IIRC that was set in a json file in VS2016 (launch.json?) but doesn't appear to be the case in VS2017.  In VS2017 the path being used for the serviceworker cache seems to be:
user/AppData/Local/Microsoft/VisualStudio/'vsversionNo'/WebTools/ChromeData{guid}/Default/ServiceWorker/CacheStorage/{guid}
FWIW 'www.google.com' has also created a folder for cache storage under that profile and it also appears to have not succeeded in storing anything.

**Comment by vivphillips** [comment]
No suggestions ?

**Comment by shirhatti** [comment]
@vivphillips While I understand you legitimately have an issue, we don't have the domain expertise about Chrome behavior to help you out.
I'm closing this issue as there's nothing actionable on our end
