### ISSUE TITLE
Version handshake between native and managed

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCoreModule#169]
For example, if ANCM is loaded with version 2.1 and an application is loaded with version 2.2, and there were pInvoke changes from 2.1 to 2.2, we need to detect that managed code does not try to call ANCM methods that do not exist.
cc @Tratcher @pan-wang @davidfowl

**Comment by pan-wang** [comment]
I think we should always put pInvoke in a try-catch. If there is any exception, the manage code should set correct http response (e.g., 500 error) and then callback ancm and let IIS pipeline continue

**Comment by davidfowl** [comment]
> I think we should always put pInvoke in a try-catch. If there is any exception, the manage code should set correct http response (e.g., 500 error) and then callback ancm and let IIS pipeline continue

That's just about exception handling though right? That ok but it seems unrelated to the general question of version detection.

This isn't a new problem and there are many ways to tackle it each with their pros and cons:

- Capability detection via exceptions
- Capability detection via function detection (GetProcAddress)
- Capability detection via explicit version check

**Comment by jkotalik** [comment]
I was thinking we add a pInvoke that returns the version of ANCM (either explicit file version or some maintained ANCM version).

**Comment by Tratcher** [comment]
Or all of the above. GetProcAddress sounds promising for detecting new methods. You may need the version check for API or behavioral breaking changes though. It's hard to say what we'll need before we need it, but surfacing the version is one thing we can do in the initial release so that we can take advantage of it later if we need to. The other suggestions sound primarily reactive.

**Comment by pan-wang** [comment]
One thing to note is that ANCM is always released as  a bundle with Asp.Net core except on Antares.

**Comment by Tratcher** [comment]
True, that helps, but it doesn't guarantee they stay in sync for scenarios like published stand-alone apps.

**Comment by davidfowl** [comment]
Adding the version can't hurt, it should be a number we manage instead of the file version though. That'll be much easier to grok. We also have to be clear on what that version number means. Ideally, we'd only change it if there was something breaking. Also, we could potentially avoid most of the hassle by adding new methods instead of changing old ones . Think of it like any other public API we maintain today

**Comment by Tratcher** [comment]
Now there's an interesting question. Do we consider these native methods as public API? They're certainly exposed publicly.
I agree on not coupling it to the file version, though there needs to be an easy way to backtrack from a file version for user reported issues.
Let's set it to 1 for now and then we can decide what merits incrementing it. Or should we go full semver? At that point we may as well use the file version.

**Comment by davidfowl** [comment]
it's pubternal.

**Comment by muratg** [comment]
Guys, do we need a design meeting to discuss this?  Or is there some simple design we can agree on for 2.1 release that @jkotalik can go ahead and implement.

**Comment by shirhatti** [comment]
@muratg We have a meeting scheduled for today, just forwarded you the invite.

**Comment by muratg** [comment]
This doesn't seem to be necessary anymore with the hostfxr changes
