### ISSUE TITLE
ASP.NET Core module runs app twice

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#247]
_From @ysmoradi on November 15, 2017 10:4_

I've multiple **ASP.NET Core 1.1** apps with **.NET 4.6.1 as a sdk target** and **.NET 4.7 as a runtime** on **Windows server 2012 R2 (6.3.9600)**. 

I've also installed **ASP.NET Core 1.1 hosting module** for an **unmanaged/integrated application pool**.

**Max worker process = 1**

IIS structure:
     App pools >> MainAppPool, AppPool1, AppPool2, AppPool3, AppPool4, AppPool5
     Web Site >> Main web site with MainAppPool
     Web Apps under main web site >> WebApp1 with AppPool1 to WebApp5 with AppPool5

MainWebSite has no process other than w3wp.exe process. (It's a simple folder)
WebApp1,3,5 have only one process for each of them + 3 processes for w3wp.exe
**WebApp2,4 have two processes for each of them** + 2 processes for w3wp.exe
So I've 13 processes instead of 11 processes.

I tried to stop/start IIS and it creates those extra processes every time.

What can cause such a problem like this?

_Copied from original issue: aspnet/IISIntegration#475_

**Comment by yasmoradi** [comment]
I've updated to .NET Core Windows server hosting 2.0.3 & .NET 4.7.1 + I've restarted server + I've installed all Windows server updates.
Nothing changed and we're experiencing this issue /-:
Shall we update to windows server 2016?

**Comment by shirhatti** [comment]
@jhkimnew Can you follow-up @ysmoradi for repro details?

**Comment by jhkimnew** [comment]
Hi, @ysmoradi 

First of all, you don't need to update OS and need to figure out why that happens.
 
Here I listed the possible reasons below. 
Could you check if this helps to figure out the reason?

1. You might set processesPerApplication with 2 for the WebApp2,4. 

2. Or, there is orphaned process while recycling the w3wp.exe worker process which was created for the Web2,4. 
(FYI, When recycling w3wp.exe, we create a new w3wp.exe and then remove the old one. If there was something bad happens and blocking to remove the old one, there can be two instance of w3wp.exe)
In that case, you can simply kill all the w3wp.exe process of either Web2 or Web4 and repeat sending requests to the app. If there is only one w3wp.exe for the app, you will need to investigate when there are two w3wp.exe processes for the app. If you see the symptom again, please give us more information when the problem happens and try to narrow down the issue to make a simple repro steps.

Thanks,
Jeong Hwan Kim

**Comment by jhkimnew** [comment]
@ysmoradi Please take a look at the event viewer logs together while you are reproducing the issue to check if there is anything suspicious log, which might be helpful to narrow down the issue.

**Comment by yasmoradi** [comment]
@jhkimnew Maximum worker processes in IIS app pool config is 1.

ASP.NET Core module config section of our web config has no value for processesPerApplication, so based on defaults, its value is 1. (To be honest, we've configured Signalr 2 without any back such as sql or redis, so, we're not interested in extra processes in any way)

I appreciate the scenario you've imagined about orphan processes. But we stopped IIS, then we killed all processes. After that we started IIS and we saw extra processes again!

I understand that this is a good idea to count IIS processes (w3wp.exe) at the same time, but I'm afraid we've not counted them. (Extra processes are not there all them time, I'll count IIS process the next time I face extra processes)

I've no idea about what produces this problem and I wasn't able to find anything about this in event logs.

We've updated our app to ASP.NET Core 2. But we've not published it yet. We try to find some more info before our new release.

Note that, we've not faced this problem in our dev environment using IIS express.

**Comment by yasmoradi** [comment]
AspNetCoreApp1-Process
AspNetCoreApp2-Process
AspNetCoreApp3-Process
AspNetCoreApp4-Process
AspNetCoreApp5-Process
**AspNetCoreApp5-Process >> Again!**

6 w3wp.exe processes which is acceptable. We've 5 asp.net core apps in separated app pools + default app pool which has no asp.net core app inside.

**Comment by jhkimnew** [comment]
Hi, @ysmoradi 

Here are some questions and suggestions.

1. I don't get what you mean with "AspNetCoreApp5-Process >> Again!". Would you give more information what you did and how you got the information? 

You did not give any detailed information. You told you only start IIS after killing all the process, which does not make sense because IIS worker process is started only when there is a request. Starting IIS usually does not start worker process automatically unless you have special IIS configuration settings such as IIS warm up features.
So, please share more information about what exactly you did before and when the issue happens for me to understand. 
I'd like to inform that w3wp.exe is real IIS worker process. So, please use task manager and shows more information about that because I have no idea what you mean with "AspnetCoreApp5-Process". 

2. I am not sure why you had to start all the process. If the problem is always reproducible with , you can use only the App5, not others, right? Please try with only App5 without running other apps. For I am confused why you show all the list of apps and if that is required to reproduce the issue. 

4. If you think this is reproducible with only specific application such as yours, not reproducible with other simple apps, please make a simple repro step and give the steps here and I can investigate with the repro steps.  I have already using ASP.NET Core 2 apps on full IIS server and I don't see this kind of issue and that's why I am asking to make a repro step. If this is reproducible with only specific app such as App5, please make a simple app which reproduce the issue and attached the source files as well. BTW, considering fact that the worker process management is done by IIS, if this is really a bug of IIS, please test if this is reproducible on specific OS version only and inform that as well to avoid any confusion.

**Comment by jhkimnew** [comment]
Hi, @ysmoradi 

Can you confirm if the App5 is an executable file such as AspnetCoreApp5.exe? Or, is it a dll file which is supposed to be launched with donet.exe? 
I will assume that it is an executable file and here is one suggestion to narrow down the issue.

Please do this.

1. Open Task manager

2. Kill all the w3wp.exe
You will see all the backend application process including the AspetCoreApp5.exe process will be killed together because all the backed application process were started by the w3wp.exe as its child process.

3. Send many requests to the App5

NOTE: 
3.1 Don’t send any request other apps to see if this issue happens with only App5
3.2 Make sure you use the exactly same app path such as http://localhost/App5, not multiple app paths such as http://localhost/foo/App5 and http://localhost/bar/App5
FYI, if you have multiple apps which use the same AspetCoreApp5.exe, that is another reason that there can be multiple instance of AspetCoreApp5.exe running together. In that case, that is by design, expected behavior with no harm.

4. Make sure only single w3wp.exe is running at this point

5. Observe if there is a single AspetCoreApp5.exe process running or not.
If so, the issue is not reproducible with App5.
If not, we have to investigate why ANCM (aspnetcore.dll) had to start two instance of AspetCoreApp5.exe. 
For your information, aspnetcore.dll has a mechanism of retrying to start the backend application process if the backend application process does not response on time. Maybe that is another possible reason of this problem. In that case, you would need to check if the detault startupTimeLimit is too short for the App5 and increase the value.

Thanks,
Jeong Hwan Kim

**Comment by jhkimnew** [comment]
@ysmoradi Is there any update on this issue?

**Comment by jhkimnew** [comment]
@ysmoradi One more thing. If the issue does not happen in dev environment, I think it is worth to check the file version of aspnetcore.dll in IISExress version the aspnetcore.dll in IIS of the repro machine in order to check if this issue happens with a specific aspnetcore.dll version or not.

**Comment by yasmoradi** [comment]
Thanks for your attention 

First of all, AspNetCoreApp5 is an executable due being compiled by full .net framework.

I can't send requests to AspNetCoreApp5 only, due this is hosted in production. All applications are under load. I try to copy virtual machine and perform this test in isolated environment. I've seen fantastic kubernetes copy/paste whole environment in azure, but we're relying on simple virtual machines and manual operations and this takes some times for us.

"FYI, if you have multiple apps which use the same AspetCoreApp5.exe" >> This is possible, but I'm sure this is not my current situation.

startUpTimeLimit's default value is 120 seconds. I'm sure our app is responsible in seconds, not minutes.

I'm gonna check aspnetcore.dll's version too and I'll report that here

**Comment by jhkimnew** [comment]
Hi @ysmoradi,
I am not clear why you are saying about Azure here? To make it clear, can I ask one more thing?
Does that mean you don't have your own IIS sever for testing purpose? Or, are you saying that the issue is  reproducible only from the application which is deployed/published to Azure? In my opinion, to make debugging easy, I think you should test using your own IIS server and that will be helpful to narrow down the issue easily. Anyway, please confirm whether this issue is reproducible only from IIS server in Azure or the same issue can be reproducible from a standalone IIS server as well.  Another important thing is that you should try to make a simple application in order to reproduce the issue and modify the app until you hit the same issue. If you just gives the symptom of your issue without giving the repro steps, there won't be easy way to figure out the root cause of this problem.

**Comment by yasmoradi** [comment]
I confirm all aspnetcore.dll versions are the same (IIS & IIS-Express of our machine and IIS of Production VM)
Yeah, we've deployed our app to Windows Server VM on azure. But I think the problem is not related to azure. We've lots of other apps with the same architecture on azure which are working really fine.
Within the next sprint, we're going to perform these actions:
1- Develop/Test on top of IIS (We can't switch from Windows 10 to Windows Server 2012 at the moment although)
2- Copy-Paste vm to test it in an isolated environment without suffering from client's requests.

We're somehow busy in delivering business requirements, but we try to do our best.
Thanks for your attention.

**Comment by jhkimnew** [comment]
@pan-wang 
I ran into a similar issue with a combined user scenario of putting app_offline.htm and removing app_offline.htm and then changing web.config file. In that case, we noticed there is reference counter is messed up and failed to recycle the application after the web.config file change happens. After the problem happens, if I send another request, there is a new backend application created, so that it causes two instance of backend application process per a single application.

**Comment by sepehr1014** [comment]
We're having this issue as well. Any updates?

**Comment by jhkimnew** [comment]
The root cause of this issue is because the app_offline.htm creates a child request to redirect the web response from original to the error message of app_offline.htm. This design is now updated in the new implementation. We don't use the child request to handle the app_offline.htm. FYI, the new ANCM implementation is on https://github.com/aspnet/iisintegration, which will be used by the next version.

**Comment by bleslie21** [comment]
Is this issue specific to using app_offline.htm?   

With core 2, we are seeing duplicate dotnet.exe and conhost processes for several apps when we just restart IIS, kill processes, and/or reset app pools manually.  We also encounter the issue with our automated deployment.  Our deployment scripts first stop the app pool, then check for any processes (w3,dotnet,conhost) still lingering and kills them, and then restarts the app pool.  

We have also noticed that with aspnet core 2 recycling app pools can take much longer (several minutes).

**Comment by pan-wang** [comment]
Could you please check windows event log to see whether ANCM tried to shutdown the backend process.

ANCM tried to graceful shutdown, i.e., waiting for all requests to drain instead of actively kill the backend.

On Server 2016, IIS also do graceful shutdown. If there is a long running request, shutdown will be held by this long running request. You can check the "activerequest" counter in perfmon of current worker process.

________________________________

**Comment by sepehr1014** [comment]
We're facing the same issue with WebDeploy on Windows Server 2016. A process is started, then after 15 seconds or so, another one is started and the original one seems to be paused. Here's the error log:

> A process serving application pool 'pasajapp.com(domain)(pool)' suffered a fatal communication error with the Windows Process Activation Service. The process id was '13472'. The data field contains the error number.

**Comment by pan-wang** [comment]
@sepehr1014 IIS uses namepipe to communicate with worker process (i.e., w3wp.exe). For your case, IIS instead of ANCM seems hitting some difficult to get response from the worker process. One possibility is the failure of loading a module, e.g., taking longer time. is there any other event logged in windows event log?

**Comment by sepehr1014** [comment]
@pan-wang I suspect app process takes a longer than expected time to start functioning. Although we have 16 physical cores running at 2.4GHz and plenty of RAM dedicated to this app, it takes about 15 seconds to start responding to requests after a cold start. (It took a lot less when using ASP.NET Classic) So maybe increasing the timeout interval might help. Also there are no event logs except the generic one I provided in the last comment.
