### ISSUE TITLE
aspnetcore!RegisterModule+9f7b aspnetcore.dll caused an access violation exception (0xC0000005)

### ISSUE THREAD

**Issue by tfsjohan** [aspnet/AspNetCoreModule#258]
I'm having a problem where a ASP.NET Core 2 app running on IIS crashes at random times and stopping the AppPool. It can run for many hours without problems and then suddenly crash.

I have tried to get help with the issue on Stack Overflow and has described some errors and warnings there:
https://stackoverflow.com/questions/47399536/asp-net-core-2-iis-apppool-crashes-and-stops

I've also used DebugDiag to get crash logs when it shuts down. I've attached an example of such dumps here. 

The app is upgraded from ASP.NET Core 1.1 and very little of the source code has changed. 

What could cause these errors and crashes?

[crashlog.zip](https://github.com/aspnet/AspNetCoreModule/files/1491985/crashlog.zip)

**Comment by jhkimnew** [comment]
Hi,

The AV happened from the line "IHttpResponse * pResponse = m_pW3Context->GetResponse();" of the below function because the m_pW3Context was pointing some valid address and therefore caused the Access Violation error.

<><><>
VOID
FORWARDING_HANDLER::OnWinHttpCompletionInternal(
    HINTERNET   hRequest,
    DWORD       dwInternetStatus,
    LPVOID      lpvStatusInformation,
    DWORD       dwStatusInformationLength
)
{
    HRESULT hr = S_OK;
    bool fIsCompletionThread = FALSE;
    bool fClientError = FALSE;
    bool fAnotherCompletionExpected = FALSE;
    DBG_ASSERT(m_pW3Context != NULL);
    __analysis_assume(m_pW3Context != NULL);
...
    IHttpResponse * pResponse = m_pW3Context->GetResponse();
...
<><><>

The m_pW3Context value was set with an invalid memory address such as 0x4489ca8b49d18b48 at that time as the following screen capture:

0:012> dv
                      this = 0x000007fe`eb4412a8
                  hRequest = 0x00000000`00000001
          dwInternetStatus = 0x1fc3f20
      lpvStatusInformation = 0x00000000`00000001
 dwStatusInformationLength = 8
              fClientError = false
fAnotherCompletionExpected = true
       __achstrDescription = wchar_t [128] ""
            strDescription = class STRU
0:012> dx -r1 ((aspnetcore!FORWARDING_HANDLER *)0x7feeb4412a8)
((aspnetcore!FORWARDING_HANDLER *)0x7feeb4412a8)                 : 0x7feeb4412a8 [Type: FORWARDING_HANDLER *]
    [=0x7feeb45ac88] sm_hSession      : 0x11dca70 [Type: void *]
    [+0x008] m_Signature      : 0x1374d285 [Type: unsigned long]
    [+0x00c] m_cRefs          : 1612989579 [Type: long]
    [+0x010] m_pW3Context     : 0x4489ca8b49d18b48 [Type: IHttpContext *]
...


Because the right W3Context object is not available, I could not figure out what really happened.

FYI, if there was the valid context object, we could tell what request URL was used with looking at its member variables but not for this case. 

Even the dwInternetStatus is set with a weird value, which seems not valid either.

@pan-wang: Can you take a look at the dump file and check if you can find any clue to fix this issue?

**Comment by fgather** [comment]
Any update on this? This is a huge showstopper for using Core 2.0 inside an IIS

**Comment by pan-wang** [comment]
@fgather this double completion issue was already fixed

**Comment by fgather** [comment]
Hi @pan-wang, you mean in #151 ? I assume there is no compiled version of the dll?

**Comment by pan-wang** [comment]
try install the latest Windows Server Hosting (.exe) from https://www.microsoft.com/net/download/windows. We always try to address customer's issue with latest release.

**Comment by shirhatti** [comment]
Closing this issue since it's already been resolved. Feel free to reopen if this issue persists.
