### ISSUE TITLE
IIS custom error pages do not work with ANCM

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#31]
_From @Tratcher on June 8, 2016 21:47_

The IIS custom error page feature allows IIS to provide/replace the response body for specific status codes. By default it will do this for 401,403,404,405,406,412,500,501,502.  However, this does not work with ANCM/Kestrel, all configured error pages are bypassed and the original body from the application is returned to the client.

Questions:
- Do we want to support IIS custom error pages with Asp.Net Core? We have a replacement feature in Diagnostics called StatusCodePages. We also have multiple 500 pages.
- If yes, should it be opt-in or opt-out? If it were opt out you would be unable to see any of the Asp.Net diagnostics pages by default.

@DamianEdwards @shirhatti @pan-wang @davidfowl 

_Copied from original issue: aspnet/IISIntegration#203_

**Comment by Tratcher** [comment]
Note we see the same behavior in Azure.

**Comment by Tratcher** [comment]
@blowdart

**Comment by Tratcher** [comment]
_From @GuardRex on June 11, 2016 16:37_

I vote for making this an opt-in feature. I enjoy keeping as much server-ish work within Kestrel as possible ... even secretly hoping that Kestrel could get the needed features to make it a full-fledged, standalone server for WS one day.

If you made this an opt-out feature, it feels like that would be leaning in the opposite direction. I hope every decision that comes down to choosing default behavior between IIS and Kestrel leans in the Kestrel direction.

**Comment by Tratcher** [comment]
_From @shirhatti on August 22, 2016 22:16_

@muratg This was by design. We don't see enough people asking for this to be done.
I'm leaving this issue open to gather feedback, but right we don't plan on changing behavior

**Comment by shirhatti** [comment]
Given that no customers has since asked for this, I'm going go ahead and close this issue as a won't fix

**Comment by c-s-n** [comment]
In case you are still interested in a use case, why this might be required to work:

When having **Windows Authentication** enabled and the browser configured to not pass-through the credentials, i.e. to show this **native browser authentication popup**, then the user is able to **cancel this popup**. The HTTP status code of the response in that case will be 401.

* If you access the page on the server via localhost, the ASP.NET Core application is capable of handling this 401 response with a (custom) StatusCodePagesMiddleware that writes to the response body.
* If you **access the page remotely**, i.e. from another computer, cancelling the authentication popup will result in the default IIS static file error page `401.htm` being shown. The ASP.NET Core application is not able to handle this.

For the latter case it would be good to have an "Execute URL" type error page working that can be pointed to a path for an ASP.NET Core application-provided page.

**Notes**
Tested on IIS 7.5 and 8.5.

**Workaround**
What we currently do is having a static error page (because that apparently still works with ANCM) that performs a JavaScript `window.location` replacement to change the failed Windows Authentication action method path to the error page route (which makes it work also for non-root-application).
