### ISSUE TITLE
How to get latest aspnetcore.dll and aspnetcore_schema.xml?

### ISSUE THREAD

**Issue by strohhut** [aspnet/AspNetCoreModule#39]
Uninstalling a previous version did not remove those files so I removed them manually. Then I installed DotNetCore.1.1.0.Preview1-WindowsHosting.exe but those files didn't come back. Shouldn't the ANCM installer put those under inetsrv and schema?

**Comment by shirhatti** [comment]
The schema is part of the repo if you want to hack it together  now https://github.com/aspnet/AspNetCoreModule/blob/dev/src/AspNetCore/aspnetcore_schema.xml

As for your specific issue, I believe repairing the installer should put all the files back
/cc @jhkimnew

**Comment by jhkimnew** [comment]
If the file (aspnetcore.dll) is still there after uninstalling, I think there is other package which depends on the ANCM installer, which is hidden on purpose. In that case, uninstalling is postponed until the other package is uninstalled. So, if you did not uninstall the package, the ANCM is considered as still being installed and the DotNetCore.1.1.0.Preview1-WindowsHosting.exe can't install ANCM again because it is still installed.

If that really happened, you removed the file manually without knowing that fact.
So, only possible solution is to repair the installed package of the DotNetCore.1.1.0.Preview1-WindowsHosting.exe in the "Add/Remove programs" in control panel and you will be able to reinstall the removed files.

**Comment by strohhut** [comment]
Repairing worked, thanks!

Since the installer said (during my initial attempt to get the files back) that the installation was successful I was confused that those files were missing. I didn't expect that repair checks if those files exist but the installation doesn't.
