### ISSUE TITLE
OS upgrade breaks ANCM

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#4]
Requires repair to fix

**Comment by shirhatti** [comment]
@jhkimnew Has this fix made it into the Win 10 insider's build yet?

**Comment by guardrex** [comment]
@shirhatti Do you want anything on this in the Pub IIS update? I gathered from your root cause analysis ...

**Application Log:** The Module DLL **C:\WINDOWS\system32\inetsrv\aspnetcore.dll** failed to load. The data is the error.

**Troubleshooting:** Non-OS files in the **C:\Windows\SysWOW64\inetsrv** directory are not preserved during an OS upgrade, If you have the ASP.NET Core Module installed prior to an OS upgrade and then try to run any Application Pool in 32-bit mode after the OS upgrade, you will encounter this issue. After an OS upgrade, repair the ASP.NET Core Module. See Install the .NET Core Windows Server Hosting Bundle.

**Comment by shirhatti** [comment]
@GuardRex What you have there sounds good 👍

**Comment by guardrex** [comment]
Ok, thanks. I'll add that in a commit today.

**Comment by shirhatti** [comment]
This issue has been fixed in Windows Insider Build 15002

**Comment by guardrex** [comment]
@shirhatti Ok for me to pull this from the *Troubleshooting* section of the *Publishing to IIS* doc now?

**Comment by Tratcher** [comment]
Let's keep it until most people have moved to 15002

**Comment by guardrex** [comment]
@Tratcher I'm doing a Pub IIS update now. Do you want to keep this common error in the *Common Errors* section for a while longer?

**Comment by Tratcher** [comment]
Yes please. The general public hasn't moved to 15002 yet.
