### ISSUE TITLE
Aspnet core module is not installed correctly

### ISSUE THREAD

**Issue by balarvs2002** [aspnet/AspNetCoreModule#52]
After installing CORE Hosting bundle in Windows server 2008 R2 then executed net stop and net start , Asp.net Core module  is not listed in IIS 7 module list, hence I am not able run application .
Any suggestion , Did I miss anything ?

Same steps worked perfectly in WS2012

**Comment by Tratcher** [comment]
Start by sharing the install logs. See https://github.com/aspnet/IISIntegration/issues/179#issuecomment-229367383

**Comment by treestryder** [comment]
Ha!

After nearly a day researching why IIS was complaining (HTTP Error 500.19 The requested page cannot be accessed because the related configuration data for the page is invalid.) about the aspNetCore node in my web.config, I finally tracked it down to the AspNetCoreModule module not being added to the applicationHost.config. Thinking that there might have been a bug in the installer, I ended up here. While piecing together the evidence, I finally figured out what had happened....

I now cannot find the original document that I was following, but it had linked to the .NET Core Runtime and not the full "Server Hosting" bundle. So though, I thought I was installing and reinstalling everything needed, it was only the run-time. Installing the Server Hosting bundle solved the problem.

I say all this, with plenty of keywords I had searched for, just in case someone else runs into a similar problem.

**Comment by muratg** [comment]
:+1:

**Comment by tkallsen** [comment]
Hi,

I'm having the same problem (module not installed in IIS / aspnetcore.dll missing under inetsrv), after running the Server Hosting Bundle (https://www.microsoft.com/net/download/thank-you/dotnet-runtime-1.1.5-windows-windows-server-hosting-installer).

I have tried uninstalling and installing a few times, with reboots in between but it doesn't seem to work. This page (https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore1x#iis-configuration) says under Troubleshooting -> "Incorrect role, module not installed, or incorrect permissions" that the ASP.NET Core Module is supposed to have an entry under installed programs, which is not true in my case. However, when I check a working Window Server 2012 installation, I don't have that there either.

Server with this problem is a virtual Windows Server 2016. Install logs attached.

[logs.zip](https://github.com/aspnet/AspNetCoreModule/files/1577444/logs.zip)

**Comment by tkallsen** [comment]
Another symptom is that IIS fails to read a web.config in IIS Manager if it contains the `<aspNetCore>`-element, but I guess that is just because the ASP.NET Core Module is missing.

**Comment by tkallsen** [comment]
I created a new issue for this, https://github.com/aspnet/IISIntegration/issues/493
