### ISSUE TITLE
How to configure purge policy on stdOut.log files?

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#83]
_From @varcario on March 29, 2017 17:8_

Does Kestrel support defining a purge policy on the stdOut.log files it writes.  So if I need to make sure my server doesn't run out of disk space.  Can I set a rolling file policy with a limit on the number of files I would like to retain, writing a new file each day, and a max disk space policy that deletes oldest files first when the max limit is met.

_Copied from original issue: aspnet/KestrelHttpServer#1568_

**Comment by guardrex** [comment]
@varcario The current guidance is only to use `stdout` logging for troubleshooting and not to use it for general logging. The current recommendation is to use one of the [third-party logging providers](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging#third-party-logging-providers), several of which have (at least some of) the features you listed. There is an issue on an official file logger that you might want to lend your support to: https://github.com/aspnet/Logging/issues/441

**Comment by shirhatti** [comment]
I'd echo what @GuardRex  has said. Feel free to re-open this issue if that doesn't work for you.

**Comment by joshmouch** [comment]
@guardrex @shirhatti 
Just from personal experience, there are a ton of exceptions that occur before any third-party logging providers are able to get injected, making stdOut logging essential.  For example, just this morning, I am dealing with an issue with an using the Azure ApplicationInsights Extension, which causes an exception that does not get picked up by ILoggerProvider (I'm using Serilog), but it does show up in the stdout.

There have been several other similar situations over the last few months.

Another example is that I'm working with Microsoft Support right now about some 500 errors that none of the Azure logs are picking up (Windows Event Log, App Insights, etc.).  The support team is telling me the only place to find information on what happened the next time this occurs is in the stdOut because they think it's a kestrel issue.

**Comment by guardrex** [comment]
@joshmouch 

>  ton of exceptions that occur

... you're seeing in the Application Event Log? Can you provide some examples?

Are you troubleshooting in Azure App Service?

**Comment by joshmouch** [comment]
Here's an example of something I'm actively looking at.  This shows up in in the stdOut log file, but not in App Insights or Database logs.

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.ApplicationInsights.SnapshotCollector.Uploader.Program' threw an exception. ---> System.IO.IOException: The process cannot access the file 'D:\local\LocalAppData\MinidumpUploader\VER.2017-10-29.12.30.54.000.new\Microsoft.Data.Services.Client.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.Diagnostics.Utilities.ResourceUtilities.UnpackResourceAsFile(String resourceName, String targetFileName, Assembly sourceAssembly)
   at Microsoft.Diagnostics.Utilities.SupportFiles.UnpackResources()
   at Microsoft.Diagnostics.Utilities.SupportFiles.UnpackResourcesIfNeeded(Boolean force)
   at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.Program..cctor()
  --- End of inner exception stack trace ---
   at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.Program.Main(String[] args)
```
