### ISSUE TITLE
ASP.NET Core app crashed on Windows 7 IIS periodically

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#96]
_From @jozefizso on May 12, 2017 9:43_

We run ASP.NET Core 1.0 app on Windows 7 SP1 machine using IIS. The application crashes from time to time.

```
Faulting application name: w3wp.exe, version: 7.5.7601.17514, time stamp: 0x4ce7afa2
Faulting module name: ntdll.dll, version: 6.1.7601.23796, time stamp: 0x590296ce
Exception code: 0xc000070a
Fault offset: 0x000000000005743a
Faulting process id: 0xf8c
Faulting application start time: 0x01d2cafaf16df27b
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: feecf471-36f6-11e7-b2da-9a19ab15f1e1
```

_Copied from original issue: aspnet/IISIntegration#370_

**Comment by francnuec** [comment]
I am having this same issue, and its driving me nuts. Similar error in Event Viewer, but I'm on Windows 10 Pro. Here's my error:

> Faulting application name: devenv.exe, version: 15.0.26430.12, time stamp: 0x59275f23
Faulting module name: ntdll.dll, version: 10.0.14393.479, time stamp: 0x58256ca0
Exception code: 0xc0000374
Fault offset: 0x000d9d11
Faulting process id: 0x22b8
Faulting application start time: 0x01d2dd6ff7461333
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 0aa8423f-5c0c-483b-b078-9ed30c5c1399
Faulting package full name: 
Faulting package-relative application ID: 

Mine started with VS 2015 Community immediately after I installed .net core 1.1.2. Suddenly all ASP.NET Core projects (including 1.0) won't run without crashing VS. I saw a solution somewhere to install VS 2017 for a possible fix. Did, and experiencing same if not worse. With VS 2015, I got an error page sometimes, but with 2017, once you run, it crashes and restarts immediately. No errors save for Event Viewer logs. 

Please kindly help with this, I can't continue my projects.  I'm almost positive my troubles started when I installed net core 1.1.2, so I'm going to try uninstalling it just to see if it works. I'm just worried about the effect it would have on the VS 2017 installation seeing .net core 1.1.2 came packaged with it.

Goes without saying that other project types work. Classic ASP.NET projects running on .NET Framework still works with no issues. Also, if the .net core projects are compiled to an executable and run standalone (without IIS, but with Kestrel only I guess), it works perfect. The issues is running the project from VS on IIS Express. Crashes instantly.

**Comment by francnuec** [comment]
So I ended up solving this a few minutes ago, after like 2-3 days on this. I really can't say these are the steps that gave me the "victory" (because I basically had tried everything at this point), nevertheless, here are the last steps I took:

1. Uninstalled .NET Core 1.1.2 (runtime + sdk).
2. Installed Remote tools for VS 2017.
3. Installed ASP.NET Core Module Windows Server Hosting package (don't know why I did this, I'm not using Windows Server nor full IIS exactly)
4. Re-installed .NET Core 1.1.2 (and other net core sdks too)
5. Found some VPN software I installed a few weeks back in Programs and Features and uninstalled it. (I did this because I also got some other errors like "but either crashed or did not response or did not listen on the given port 'xxxx'" sometimes in Event Viewer)
6. Restarted Windows.

And it worked. Put this here in case someone else might be going through this too, but really, I don't understand what I did here. I'm just thankful to be debugging again. :)

Cheers.

**Comment by shirhatti** [comment]
Unfortunately, there isn't enough to go off here.
@jozefizso If you do see this issue again, please try and capture a dump for `w3wp.exe`.

@francnuec Your issue different since it seems like Visual Studio is the process that crashes and not IIS Express. @BillHiebert Have you seen this issue before?

**Comment by muratg** [comment]
No updates / no repro. Closing this one.  Please file another one with W3WP dump if you're still having issues.
